# Generated by Django 2.1.1 on 2018-10-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchname', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Registration_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=30)),
                ('Parents_Email', models.EmailField(max_length=30)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_home.Branch')),
            ],
        ),
    ]
