# Generated by Django 2.1.1 on 2018-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Parents_Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Registration_No',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
